### PR TITLE
Add alternate rom list

### PR DESCRIPTION
**Pull request by catskull**

### CODE REVIEW

**Comment by dcasella** [comment]
Ah, oki

**Comment by avivace** [comment]
I was already aware of that list but this is GB/DMG only. But adding a parallel document for additional GBC tools and resources is an idea.

**Comment by catskull** [comment]
Okay, fair enough. I just though this might be a bit more navigable than the google doc was. But I can see where you're coming from.

Out of curiosity, what difference is there in the actual development tools for GBC? I was under the impression that most tools are basically the same for both.

**Comment by avivace** [comment]
Basically the tools are the same, the GB games runs on GBC but creating a game for GBC actually means taking advantage of the specific capabilities and different hardware.
I definitely plan to add a GBC section, It would be a great add.

**Pull request closed without merging**
