### PR TITLE
Sort, split, correct and add

### PR DESCRIPTION
**Pull request by ISSOtm**
Lots of work. Not sure ALL will be merged, but the sorting and splitting definitely would merit to.

### CODE REVIEW

**Comment by avivace** [comment]
This all makes sense.

1. I really don't like is the constant division between ASM and C for a lot of categories. Is this really necessary?
In Tools, it'll be demanding to constantly check if a possible entry works with ASM, C or in some way with both.
I feel there's a real need to point out what development "system" are we refering to but maybe there's a better way?

2. We also need a way to categorize the "Related  Projects" because a lot of different and relevant projects went there without much recognition.

3. There's no need for a *General*, *Other* or *Misc* sub category you added in Documentation and Tools. This doesn't really add any info and just spams. The initial list is supposed to be generally categorised. Sub categories further discriminate the other entries.

**Comment by ISSOtm** [comment]
1. The segregation between ASM and C was done because there is an actual split in the needs of ASM programmers and C programmers. For example, opcode tables, or timing-related documents (timing because you can't really toy with timing when you don't control the ASM output).
  Splitting - while indeed giving a sense of division - helps users navigate through the documentation, which I felt was quite monolithic and difficult to navigate for new users.
  A way to maybe reduce that segregation feeling would be to keep the sections splitted, but not put any individual links in the summary.

2. Isn't affected by any of the changes I made, so for the sake of simplicity I'll declare it off-topic and skip.

3. The point of specifically the "General" category was to place documents relating to how the Game Boy globally worked first, and *then* documents that were specific to each language. This one I feel justified.
   Now, "Other" and "Misc." exist for the reason that a comment specifies in the source : they contain entries that couldn't fit any other sub-categories, and didn't justify creating a new one on their own. Maybe creating a category with only 1 entry could be fine, but I didn't want to try.

**Comment by tobiasvl** [comment]
I also agree that it's useful to have a clear split between C and ASM. I can't really see a need to have them bunched together. ASM developers don't care about C stuff, and most GBDK developers don't care about ASM (until they need to implement something specific in ASM, at which point they need to look for ASM tutorials).

**Comment by avivace** [comment]
Also
> Note : it is also strongly recommended to read General Documentation before GBDK documentation. GBDK expects the programmer to already have some knowledge (even light) of how the Game Boy works.

How is this useful? 90% of the resources are either technical or require insights on the system, why is this particular for GBDK resources?

**Comment by ISSOtm** [comment]
I added this specifically because from seeing many issues that arose on the forums from GBDK users, these all boiled down to not understanding how the system was working. It almost felt like they were expecting GBDK to mask away the details, so I added this line to push people away from that pitfall.

**Comment by avivace** [comment]
A part from the ASM/C splitting in every section, every improvement has been implemented

**Pull request closed without merging**
