### PR TITLE
Copy "To C Or Not To C" writeup

### PR DESCRIPTION
**Pull request by ISSOtm**
According to Discord's log, it's been a month now. I'm not late, am I?

### CODE REVIEW

**Comment by avivace** [comment]
Thank you, should we now link this copy of the article instead of the gist?

**Comment by ISSOtm** [comment]
Sure thing. I will try to keep both copies updated, if I ever touch them again.

**Comment by avivace** [comment]
I'm not sure it makes sense to have two copies. If you want to keep your gist, we'll just keep that linked (and eventually mirror it in the gb-archive) but no sense having a copy in this repositories if we are not "using" it.

**Comment by ISSOtm** [comment]
I'd rather keep the old copy as well, to avoid breaking any links to it.

**Pull request merged**
